AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for NGINX ECS service using Fargate launch type

Parameters:
  VpcId:
    Type: String
    Description: Vpc Id
    Default: "vpc-0395fea5268cb00b5"
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs where the loan balancer will be placed
    Default: "subnet-08db821a1ab864f21, subnet-0f7b7d413758e1ad1"
  DesiredCount:
    Type: Number
    Default: 1
    Description: The number of tasks to run in the service

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: hello-world-ecs-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TaskExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: nginx-container
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group allowing traffic from internet
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "86.18.138.129/32"

  ECSFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: nginx-service
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref PublicSubnetIds
          SecurityGroups: [!GetAtt ECSSecurityGroup.GroupId]
          AssignPublicIp: "ENABLED"
